# Generated by Django 3.2 on 2021-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210303_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentImage',
            field=models.ImageField(blank=True, null=True, upload_to='contents'),
        ),
    ]
