# Generated by Django 3.2 on 2021-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentImage',
            field=models.ImageField(blank=True, null=True, upload_to='contents/'),
        ),
    ]
