# Generated by Django 3.2 on 2021-04-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_post_contentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentImage',
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='contents/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.post')),
            ],
        ),
    ]
