# Generated by Django 3.2 on 2021-04-20 07:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
