# Generated by Django 3.2 on 2021-04-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('#ffffff', '白'), ('#000000', '黒')], default='#ffffff', max_length=7, verbose_name='文字色'),
        ),
    ]
